services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-intro
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:1.19-alpine
    container_name: php-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    image: mysql:8.0
    container_name: php-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: php-adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db_data:
